### PR TITLE
Use build in websockets

### PR DESCRIPTION
**Pull request by Jarno458**
Uses System.Net.Websockets for netstandard 2.0 and newer for websockets rather than websocket sharp

### CODE REVIEW

**Comment by Jarno458** [comment]
While this works, it does not support Per Message Compression until .Net 6+, so we could add a build target for .Net 6 and upwards to use it, but i guess we just keep websocket-sharp instead

**Comment by Jarno458** [comment]
It might still be possiable using https://www.tpeczek.com/2017/07/websocket-per-message-compression-in.html

**Comment by Jarno458** [comment]
So seems like the websocket-sharp we use is totally broken on .net core. so we will revive this idea

**Comment by Jarno458** [comment]
Struggling a lot to get .Net 6 to build, ill plan building .Net 6 in a different branch so it wont affect this change, as there should only be a few lines differences on .Net 6

**Review by Ijwu — APPROVED** [review]
Thanks, feel free to merge!

**Pull request merged**
